project:
  type: website

website:
  title: ""
  image: "images/Visual analytics 1.png"
  favicon: "images/Visual analytics 1.png"
  page-navigation: true
  navbar:
    logo: "images/Visual analytics 1.png"
    title: false
    search: true
    left: 
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3(a)"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "Hands-on Exercise 3(b)"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
          - text: "Hands-on Exercise 4(a)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
          - text: "Hands-on Exercise 4(b)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
          - text: "Hands-on Exercise 4(c)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
          - text: "Hands-on Exercise 4(d)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 2"
            href: "https://public.tableau.com/app/profile/jianyi.li/viz/In-classExercise2_17456547307330/Dashboard1"
          - text: "In-class Exercise 3"
            href: "https://public.tableau.com/app/profile/jianyi.li/viz/In-classExercise3_17462581267610/In-classExercise3"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 6"
            href: "https://public.tableau.com/app/profile/jianyi.li/viz/In-classExercise6_17480710454870/Visitorarrivalsbycountry2010-2019"
          - text: "In-class Exercise 7"
            href: "https://jianyivaa.shinyapps.io/In-class_Ex07/"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1 - Phrase 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01a.html"
          - text: "Take-home Exercise 1 - Phrase 2"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01b.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
      - text: "Group Project"
        href: "Project/project.html"

    right:
      - icon: house
        href: index.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    # code-fold: true
    # code-summary: "Click to view code"


